# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} to Install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: yarn --frozen-lockfile
    - name: Run Linting
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: yarn lint
    - name: Generate Site
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    run: yarn generate
    - name: Setup Credentials
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://xayer:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    - name: Deploy Site
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: yarn deploy